spring:
  datasource:
    url: jdbc:h2:mem:patient-management
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      encoding: utf-8
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
